<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MediaCompany.Capability\MediaCompany.Capability.csproj" />
    <ProjectReference Include="..\..\src\MediaCompany.Credentials\MediaCompany.Credentials.csproj" />
    <ProjectReference Include="..\..\src\MediaCompany.Deterministic\MediaCompany.Deterministic.csproj" />
  </ItemGroup>
</Project>
